### ISSUE TITLE
Movie search coming up blank on all movies

### ISSUE THREAD

**Issue by smokinpuppy** [edouardpoitras/jasper-movies#1]
Hi, Great module idea. I'm having an issue though, when I try to do a search for any movie, it comes back saying "Unable to find information on the requested movie" What am I missing?

Thank,

Robert

**Comment by edouardpoitras** [comment]
Hey Robert,

Thanks for using the jasper-movies module!  I appreciate your help.

A few questions if you have a bit of time:
- What version/branch of Jasper and jasper-movies were you using?
- Do you get the error immediately after searching for a movie, or when selecting a movie from Jasper's options?

Thanks!

**Comment by edouardpoitras** [comment]
A couple more questions:
- What were the search queries you tried?
- What machine/platform are you doing this on?

If you haven't already, could you try again with the `--local` flag (`python jasper.py --local`) and see if you get similar results.

**Comment by smokinpuppy** [comment]
Hi Edouard,

Thanks for your quick reply, I'm actually using all your modules, they are all really nice. I'm using the current master branch of Jasper and Jasper-Movies. I get the "error" right after I get the "movie" command running. Jasper just says "Unable to find information on that movies" I tried Star Wars and Star Wars the force awakens and iron man, all came back the same.

Under --local I get the same reply plus an empty array [ ]

**Comment by edouardpoitras** [comment]
This is quite strange.  I can't seem to reproduce this issue.

Let's try this.  Run the following commands and paste the output in this thread:
- `uname -a`
- `python --version`
- `python -c "import imdb; print imdb.__version__"`

Also, please paste the full transcript of the interaction with Jasper using the debug flag: `python jasper.py --local --debug`

Hopefully we can figure this out!

**Comment by smokinpuppy** [comment]
Thank you :)
okay, here are the outputs:
uname -a = Linux ai 4.1.7-v7+ #817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015 armv7l GNU/Linux
python --version = Python 2.7.3
python -c "import imdb; print imdb.**version**" = 4.9

And here is the debug output:

---

DEBUG:client.diagnose:Checking network connection to server 'www.google.com'...
DEBUG:client.diagnose:Network connection working
DEBUG:**main**:Trying to read config file: '/home/pi/.jasper/profile.yml'
DEBUG:client.diagnose:Checking network connection to server 'www.google.com'...
DEBUG:client.diagnose:Network connection working
DEBUG:client.diagnose:Checking executable 'aplay'...
DEBUG:client.diagnose:Executable 'aplay' found: '/usr/bin/aplay'
DEBUG:client.diagnose:Checking executable 'flite'...
DEBUG:client.diagnose:Executable 'flite' found: '/usr/bin/flite'
DEBUG:client.brain:Looking for modules in: '/home/pi/jasper/client/modules'
DEBUG:client.brain:Found module 'Birthday' with words: ['BIRTHDAY']
DEBUG:client.brain:Found module 'Evernote' with words: ['NOTE']
DEBUG:client.brain:Found module 'FaceRec' with words: ['CAN', 'DO', 'YOU', 'SEE', 'ME', 'WHO', 'AM', 'I']
DEBUG:client.brain:Found module 'Gmail' with words: ['EMAIL', 'INBOX']
DEBUG:client.brain:Found module 'HN' with words: ['HACKER', 'NEWS', 'YES', 'NO', 'FIRST', 'SECOND', 'THIRD']
DEBUG:client.brain:Found module 'Joke' with words: ['JOKE', 'KNOCK KNOCK']
DEBUG:client.brain:Found module 'Life' with words: ['MEANING', 'OF', 'LIFE']
DEBUG:client.brain:Found module 'MPDControl' with words: ['MUSIC', 'SPOTIFY']
DEBUG:client.brain:Found module 'Movies' with words: ['movie', 'movies', 'yes']
DEBUG:client.brain:Found module 'News' with words: ['NEWS', 'YES', 'NO', 'FIRST', 'SECOND', 'THIRD']
DEBUG:client.brain:Found module 'Notifications' with words: ['FACEBOOK', 'NOTIFICATION']
DEBUG:client.brain:Found module 'Status' with words: ['STATUS']
DEBUG:client.brain:Found module 'Time' with words: ['TIME']
DEBUG:client.brain:Found module 'Twitter' with words: ['TWITTER', 'TWITTER NOTIFICATIONS', 'DIRECT MESSAGE', 'FEED', 'TWEET', 'TRENDING', 'NOTIFICATION', 'NOTIFICATIONS']
DEBUG:client.brain:Found module 'Unclear' with words: []
DEBUG:client.brain:Found module 'Weather' with words: ['WEATHER', 'TODAY', 'TOMORROW']
DEBUG:client.brain:Found module 'knowledged' with words: ['WHO', 'WHAT', 'HOW MUCH', 'HOW MANY', 'HOW OLD']
ALICE: How can I be of service, Robert?
DEBUG:client.brain:Looking for modules in: '/home/pi/jasper/client/modules'
DEBUG:client.brain:Found module 'Birthday' with words: ['BIRTHDAY']
DEBUG:client.brain:Found module 'Evernote' with words: ['NOTE']
DEBUG:client.brain:Found module 'FaceRec' with words: ['CAN', 'DO', 'YOU', 'SEE', 'ME', 'WHO', 'AM', 'I']
DEBUG:client.brain:Found module 'Gmail' with words: ['EMAIL', 'INBOX']
DEBUG:client.brain:Found module 'HN' with words: ['HACKER', 'NEWS', 'YES', 'NO', 'FIRST', 'SECOND', 'THIRD']
DEBUG:client.brain:Found module 'Joke' with words: ['JOKE', 'KNOCK KNOCK']
DEBUG:client.brain:Found module 'Life' with words: ['MEANING', 'OF', 'LIFE']
DEBUG:client.brain:Found module 'MPDControl' with words: ['MUSIC', 'SPOTIFY']
DEBUG:client.brain:Found module 'Movies' with words: ['movie', 'movies', 'yes']
DEBUG:client.brain:Found module 'News' with words: ['NEWS', 'YES', 'NO', 'FIRST', 'SECOND', 'THIRD']
DEBUG:client.brain:Found module 'Notifications' with words: ['FACEBOOK', 'NOTIFICATION']
DEBUG:client.brain:Found module 'Status' with words: ['STATUS']
DEBUG:client.brain:Found module 'Time' with words: ['TIME']
DEBUG:client.brain:Found module 'Twitter' with words: ['TWITTER', 'TWITTER NOTIFICATIONS', 'DIRECT MESSAGE', 'FEED', 'TWEET', 'TRENDING', 'NOTIFICATION', 'NOTIFICATIONS']
DEBUG:client.brain:Found module 'Unclear' with words: []
DEBUG:client.brain:Found module 'Weather' with words: ['WEATHER', 'TODAY', 'TOMORROW']
DEBUG:client.brain:Found module 'knowledged' with words: ['WHO', 'WHAT', 'HOW MUCH', 'HOW MANY', 'HOW OLD']
INFO:apscheduler.scheduler:Scheduler started
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:No jobs; waiting until a job is added
INFO:apscheduler.scheduler:Added job "Notifier.gather" to job store "default"
INFO:client.conversation:Starting to handle conversation with keyword 'ALICE'.
DEBUG:client.conversation:Started listening for keyword 'ALICE'
DEBUG:client.conversation:Stopped listening for keyword 'ALICE'
INFO:client.conversation:Keyword 'ALICE' has been said!
DEBUG:client.conversation:Started to listen actively with threshold: True
YOU: DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2015-12-22 23:22:42.666143+00:00 (in 29.986899 seconds)
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2015-12-22 23:23:12.666143+00:00 (in 29.997655 seconds)
INFO:apscheduler.executors.default:Running job "Notifier.gather (trigger: interval[0:00:30], next run at: 2015-12-22 23:23:12 UTC)" (scheduled at 2015-12-22 23:22:42.666143+00:00)
INFO:apscheduler.executors.default:Job "Notifier.gather (trigger: interval[0:00:30], next run at: 2015-12-22 23:23:12 UTC)" executed successfully
DEBUG:apscheduler.scheduler:Looking for jobs to run
INFO:apscheduler.executors.default:Running job "Notifier.gather (trigger: interval[0:00:30], next run at: 2015-12-22 23:23:12 UTC)" (scheduled at 2015-12-22 23:23:12.666143+00:00)
DEBUG:apscheduler.scheduler:Next wakeup is due at 2015-12-22 23:23:42.666143+00:00 (in 29.994379 seconds)
INFO:apscheduler.executors.default:Job "Notifier.gather (trigger: interval[0:00:30], next run at: 2015-12-22 23:23:42 UTC)" executed successfully
DEBUG:apscheduler.scheduler:Looking for jobs to run
INFO:apscheduler.executors.default:Running job "Notifier.gather (trigger: interval[0:00:30], next run at: 2015-12-22 23:23:42 UTC)" (scheduled at 2015-12-22 23:23:42.666143+00:00)
DEBUG:apscheduler.scheduler:Next wakeup is due at 2015-12-22 23:24:12.666143+00:00 (in 29.990976 seconds)
INFO:apscheduler.executors.default:Job "Notifier.gather (trigger: interval[0:00:30], next run at: 2015-12-22 23:24:12 UTC)" executed successfully
DEBUG:apscheduler.scheduler:Looking for jobs to run
INFO:apscheduler.executors.default:Running job "Notifier.gather (trigger: interval[0:00:30], next run at: 2015-12-22 23:24:12 UTC)" (scheduled at 2015-12-22 23:24:12.666143+00:00)
DEBUG:apscheduler.scheduler:Next wakeup is due at 2015-12-22 23:24:42.666143+00:00 (in 29.992442 seconds)
INFO:apscheduler.executors.default:Job "Notifier.gather (trigger: interval[0:00:30], next run at: 2015-12-22 23:24:42 UTC)" executed successfully

Thank you in advance for all your help!

**Comment by edouardpoitras** [comment]
Hey Robert,

Turns out the imdbpy python module has some issues in version 4.9.  I believe it has something to do with the IMDB website changing some of the structure of the page - and the 4.x branch not being updated anymore.

I updated the installation instructions to specifically install version 5.0 or higher.

You can try a `sudo pip install --upgrade "imdbpy>=5.0"`.  If that gives you any trouble (it did for me for some reason), try uninstalling the current version of imdbpy first, then installing version 5.0:

```
sudo pip uninstall imdbpy
sudo pip install "imdbpy>=5.0"
```

Hope this works!

**Comment by smokinpuppy** [comment]
Hey Edouard,

Your the best, that worked and the module is working now. Thank you,

Robert

**Comment by edouardpoitras** [comment]
Great to hear!
